# Generated by Django 3.0.4 on 2020-03-22 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid1, editable=False)),
                ('name', models.CharField(blank=True, default='Wallet', max_length=128, null=True, verbose_name='Wallet name')),
                ('description', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Wallet description')),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=50, verbose_name='Wallet funds')),
                ('currency', models.IntegerField(blank=True, choices=[(0, 'EUR'), (1, 'USD')], default=0, null=True, verbose_name='Wallet currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User wallet',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, db_index=True)),
                ('action_type', models.IntegerField(blank=True, choices=[(0, 'deposit'), (1, 'charge'), (2, 'withdraw'), (3, 'payment')], default=0, null=True)),
                ('comment', models.TextField(blank=True, help_text='Comment of the action.')),
                ('delta', models.DecimalField(decimal_places=8, default=0, max_digits=50)),
                ('created_by', models.ForeignKey(help_text='User who performed the action.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Wallet')),
            ],
            options={
                'verbose_name': 'Wallet Action',
            },
        ),
    ]
