# Generated by Django 3.0.4 on 2020-03-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.IntegerField(blank=True, choices=[(0, 'deposit'), (1, 'charge'), (2, 'withdraw'), (3, 'payment'), (4, 'insufficient funds')], default=0, null=True),
        ),
    ]
