# Generated by Django 3.0.4 on 2020-03-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20200322_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_corrupted',
            field=models.BooleanField(default=False),
        ),
    ]
